# render.yaml
# The final, correct blueprint for the ScooterBNB application.

version: "1"

services:
  - type: web
    name: scooterbnb
    runtime: ruby
    plan: free
    region: virginia # From your export
    
    # THE FIX: Use our reliable build script.
    buildCommand: './bin/render-build.sh'
    
    # A more robust start command for a production Rails app.
    startCommand: 'bundle exec puma -C config/puma.rb'
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scooterbnb-db # Matches the database name below
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false # You will set this in the dashboard on deploy.
      - key: CLOUDINARY_URL
        sync: false # You will set this in the dashboard on deploy.
      - key: WEB_CONCURRENCY
        value: 2 # Recommended for free instances.

databases:
  - name: scooterbnb-db # This name MUST match fromDatabase above
    databaseName: scooterbnb_db # From your export
    user: scooterbnb_db_user # From your export
    plan: free
    region: virginia # From your export